---
swagger: "2.0"
info:
  description: "This is a simple API"
  version: "1.0.0"
  title: "Simple museum API"
  contact:
    email: "dassbosch50@gmail.com"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/"
tags:
- name: "developers"
  description: "Operations available to regular developers"
schemes:
- "https"
paths:
  /museums:
    get:
      tags:
      - "developers"
      summary: "searches museum"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "getAllMuseum"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Museum"
        "400":
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
  /nearlyMuseum:
    get:
      tags:
      - "developers"
      summary: "searches museum"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "getNearlyMuseum"
      produces:
      - "application/json"
      parameters: []
      responses:
        "200":
          description: "search results matching criteria"
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Museum"
        "400":
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
  /museums/{museumId}:
    get:
      tags:
      - "developers"
      summary: "searches museum"
      description: "By passing in the appropriate options, you can search for\navailable\
        \ inventory in the system\n"
      operationId: "getMuseumById"
      produces:
      - "application/json"
      parameters:
      - name: "museumId"
        in: "path"
        description: "ID of pet to return"
        required: true
        type: "string"
      responses:
        "200":
          description: "search results matching criteria"
          schema:
            $ref: "#/definitions/Museum"
        "400":
          description: "bad input parameter"
      x-swagger-router-controller: "Developers"
definitions:
  Museum:
    type: "object"
    required:
    - "city"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      city:
        type: "string"
      pictures:
        type: "array"
        xml:
          name: "photoUrl"
          wrapped: true
        items:
          type: "string"
      phone:
        type: "string"
      long:
        type: "number"
      lat:
        type: "number"
    xml:
      name: "Musium"
    example:
      city: "city"
      phone: "phone"
      name: "name"
      id: 0
      pictures:
      - "pictures"
      - "pictures"
